/***********TABLESPACES***********/

CREATE TABLESPACE ZUP_DT --Tablespace de dados.
	DATAFILE 'D:/ZUP_DT.dbf' --Verifique se e necessario alterar o caminho do diretorio.
	SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ZUP_IDX --Tablespace de indices.
	DATAFILE 'D:/ZUP_IDX.dbf' --Verifique se e necessario alterar o caminho do diretorio.
	SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
  
/***********ROLES***********/

CREATE ROLE RO_ZUP; --Role da aplicacao.

/***********USERS***********/

CREATE USER BD_ZUP IDENTIFIED BY BDZUP --Usuario proprietario dos objetos de banco de dados. Verifique se e necessario alterar a senha do usuario.
DEFAULT TABLESPACE ZUP_DT
QUOTA UNLIMITED ON ZUP_DT
QUOTA UNLIMITED ON ZUP_IDX
ACCOUNT LOCK;

CREATE USER BDZUP IDENTIFIED BY BDZUP --Usuario utilizado pela aplicao para se conectar no banco de dados. Verifique se e necessario alterar a senha do usuario.
DEFAULT TABLESPACE ZUP_DT 
QUOTA UNLIMITED ON ZUP_DT;

/***********TABLES*************/

CREATE TABLE BD_ZUP.TB_PRODUCT
(
	ID_PRODUCT NUMBER(11) NOT NULL,
	NM_NAME VARCHAR2(150 CHAR) NOT NULL,
	DS_DESCRIPTION VARCHAR2(1000 CHAR) NOT NULL,
	VL_PRICE NUMBER(11, 0) NOT NULL,
	NM_CATEGORY VARCHAR2(150 CHAR) NOT NULL,
	CONSTRAINT PK_PRODUCT PRIMARY KEY (ID_PRODUCT)
);

/***********SEQUENCES***********/

CREATE SEQUENCE BD_ZUP.SQ_PRODUCT
	INCREMENT BY 1
	START WITH 1
	NOCACHE;


/***********GRANTS***********/

GRANT RO_ZUP TO BDZUP;

GRANT SELECT, INSERT, UPDATE, DELETE ON BD_ZUP.TB_PRODUCT TO RO_ZUP;

GRANT SELECT ON BD_ZUP.SQ_PRODUCT TO RO_ZUP;

GRANT CREATE SESSION TO BDZUP;