BEGIN

INSERT INTO BD_ZUP.TB_PRODUCT (ID_PRODUCT, NM_NAME,DS_DESCRIPTION, VL_PRICE, NM_CATEGORY) VALUES (BD_ZUP.SQ_PRODUCT.NEXTVAL, 'Mouse', 'Microsoft 1000', 245.00, 'Eletrônico');
INSERT INTO BD_ZUP.TB_PRODUCT (ID_PRODUCT, NM_NAME,DS_DESCRIPTION, VL_PRICE, NM_CATEGORY) VALUES (BD_ZUP.SQ_PRODUCT.NEXTVAL, 'Mouse PAD', 'Razer Moba', 200.00, 'Eletrônico');

COMMIT;
END;